### ISSUE TITLE
Suggestion to depreciate parting dimensions and gravity directions in ProcessManager

### ISSUE THREAD

**Issue by camonroe** [wwarriner/casting_geometric_toolsuite#14]
Looks like parting dimensions and gravity directions could be deprecated moving forward. This could be enabled more by rotation rather than rerunning results.

**Comment by wwarriner** [comment]
Depreciated in previous commit. Preferred means of rotation is to pass a Rotation() object to the rotate() method on a Casting() object prior to downstream analyses.
